AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  LoggingLevel:
    Type: String
    Default: INFO
    Description: Setting to WARN or below will disable.

Resources:
  EventTestTarget:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: ./dist/testTarget.js
      Handler: testTarget.handler
      Tracing: Active
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          LOGGING_LEVEL: !Ref LoggingLevel

Outputs:
  EventTestTargetFunctionName:
    Value: !Ref EventTestTarget
    Export:
      Name: !Sub ${AWS::StackName}-EventTestTargetFunctionName
  EventTestTargetFunctionArn:
    Value: !GetAtt EventTestTarget.Arn
    Export:
      Name: !Sub ${AWS::StackName}-EventTestTargetFunctionArn